def intro():
    print("After a hundred years of fighting against the legions of terror \n"
        "awakened by the wizard Ramaty, the races of Lyzarb triumphed and \n"  
        "peace reigned again throughout the known world.\n"
        "\n"
        "The consequences of these hundred years of struggle have been that \n"
        "the world has returned almost to barbarism. What were once great \n"
        "kingdoms are now nothing more than simple villages scattered here \n"
        "and there.\n"
        "\n"
        "Some kingdoms managed to rise again with their rightful heirs, \n"    
        "others disappeared forever, and many new ones emerged. \n"   
        "Then came the age of the Wizards.\n"  
        "\n"
        "This era was marked by the emergence of great mages, some dedicated \n"
        "to rebuilding the lands devastated by legions of terror, others \n"
        "dedicated only to increasing their powers. \n"
        "\n"
        "Among these wizards, one emerged who stood out for his power, he \n"
        "was called Berdolock.\n"
        "\n"
        "Holder of great power and wealth, he decided to build for himself \n"
        "something with which future generations would remember his great \n"
        "power.\n"
        "\n"
        "So he built a fortress to hold all his treasures and knowledge. The \n"
        "site chosen for construction beyond the northern mountain ranges and \n"
        "mountains, through Death Valley, within the dense mists of the Black \n"
        "Forest was the site chosen to build his Fortress, known as the \n"
        "Dark Tower, symbol of Berdolock's power and wealth.\n"
        "\n"
        "For its construction, Berdolock used his power to force several \n"
        "nearby villages to work as slaves in the construction of his \n"
        "Fortress.\n"
        "\n"
        "During its construction many died and in the end those who managed \n"
        "to survive, were either sacrificed to the dark gods or cursed to \n"
        "live in the dungeons of the Tower as monsters to guard their \n"
        "treasures and secrets.\n"
        "\n"
        "But one managed to escape, and he told everyone he saw and his story\n"
        "spread with the wind throughout the known land, provoking among the\n"
        "adventurers a great greed for the treasures that the Fortress\n"
        "possessed.\n"

        "Many ventured out, but none returned to confirm the survivor's story.\n"
        "There will always be an adventurer willing to risk his life for the\n"
        "riches and glories that the Fortress hides.\n"
        "\n"
        "Are you one of them?\n")